version: '3.8'

services:
  app:
    build: .
    container_name: rag_app
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: rag_db
    environment:
      POSTGRES_DB: rag
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  ui:
    build: ./ui
    container_name: rag_ui
    ports:
      - "8501:8501"
    depends_on:
      - app